# **Tarea Nº 1**

Curso:          Fundamentos de Programación en Python para Macroeconomía y Finanzas     
Profesor:       Victor Fuentes Campos

- Fecha y hora de entrega: Jueves 4 de enero, 11:59pm
- Agregue los nombres de las personas con las que discutió esta tarea: ____ Anghely Lozano Rojas ______Rojas Angel Emanuel
- Envíe su tarea haciendo el `push` de su código a su repo en GitHub Classroom:

# 1. Git


a. Commit, Push, Pull

Instrucciones:
1. Cada miembro del equipo debe clonar el repo de su tarea en su computadora
1. Luego, en el branch master (`main`), el integrante Nº 1 cambia el nombre del archivo `.ipynb` a `tarea_1.ipynb`
1. Usando GitHub Desktop, el integrante Nº 2 notará que hay cambios en el repo. Por lo tanto, hará el `pull` de la nueva versión del repo. Ahora ambos tiene el archivo con el nombre apropiado en sus computadoras

*Este ejercicio se calificará directamente en GitHub*

b. Merge conflicts (opcional)

1. El integrante Nº 1 abre un branch nuevo `merge_conflict_practice_1`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 2 abre un branch nuevo `merge_conflict_practice_2`. En el archivo `tarea_1.ipynb` reemplazará "Armando Paredes" por su nombre. Luego, hará `commit`y `push` de a GitHub. (En Github Desktop se llama `publish`)
1. El integrante Nº 1 hará un `pull request`
1. El integrante Nº 2 hará el `review` del `pull request`, aceptará los cambios de su compañero y hará `merge` del branch al `master`. ¡Listo, completaste tu primer pull request!
1. El integrante Nº 2 hará un `pull request`
1. El integrante Nº 1 hará el `review` del `pull request` y habrá un `merge conflict` poeque ambos están cambiando la misma línea de código. Ajuste el archivo y complete el `merge``
Cambie de roles y fuerce un `merge conflict` con una sección diferente del archivo `tarea_1.ipynb` (Fecha de entrega, nombre del curso, etc.)
1. Explique muy brevemente porque se generó el `merge conflict`

*Respuesta: __Un conflicto de fusión se genera cuando dos o más ramas contienen cambios en la misma línea de código. En este caso, el conflicto se genera porque ambos integrantes están cambiando el nombre del autor del código____________________________*

# 2. Variables

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [ ]:
monthly_savings = 10 ff
num_months = 12
intro = "Hello! How are you?"

a. Calculate year_savings using monthly_savings and num_months
: year_savings = monthly_savings * num_months

In [ ]:
# Calculate the product of monthly_savings and num_months

b. Print the type of year_savings : print(type(year_savings))

In [ ]:
# What do you think the resulting type will be? Find out by printing out the type of year_savings.

c. Assign sum of intro and intro to doubleintro : doubleintro = intro + intro

In [ ]:
# Calculate the sum of intro and intro and store the result in a new variable doubleintro.

d. Print out doubleintro : print(doubleintro)

In [ ]:
# Print out doubleintro. Did you expect this?

# 3. Lists

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [ ]:
import numpy as np
f_list = ["Brazil", np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
text1 = ['My', 'new', 'teacher', 'assistant', 'is', 'so', 'boring.']
p1_list = [ 2 , 3, 4, 5 , 6 ]
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1, 91 ]
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

a. Show the indices of the `np.nan`` values in the `f_list` list. We want to see this output: *The indices 1, 2, 5, 8 have np.nan values*. Hint: Use print function and f-strings to insert the indices values : respuesta es que los índices de los valores np.nan en la lista f_list son 1, 2, 5 y 8.

In [ ]:
# Show indices for np.nan values

b. Replicate 4 times the values of the list `p1_list`. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.: : la respuesta es Replicate 4 times the values of the list p1_list [2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

In [ ]:
# Replicates p1_list

c. Print the length of `f_list`. **Hint: Length function** Print the length of f_list 10

In [ ]:
# Lenngth of f_list

d. Print `My new teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)** la respuesta es My new teacher assistant is so boring

In [ ]:
# Printing

e. Using `values1`, print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**
 la respuesta es The max value of values1 is 86 and is located in the 0 index. The min value of values1 is 0 and is located in the 7 index.<br>

In [ ]:
# Printing

f. Get two lists: `given_names` and `last_names` using `last_and_name` list. **Hint: Use `map` and `split`.**

In [ ]:
# Two lists

g. (Opcional) Give only the last names of students who do not have email. Use the `emails` and `last_names` listt. **Hint: Use `map` and `split`.**

In [ ]:
# List of of those who do not have email

# 4.   Tuple

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [ ]:
tuple1 = ("Orange", [10, 20, 30], (5, 15, 25))
tuple2 = ([7, 8], [9, 1], [10, 7])

1. Print the first item of the second item of tuple1 object: respuesta es 10

In [ ]:
# Print

2. Print the last item of the tuple1 object: respuesta es 5

In [ ]:
# Print

3. Change the value "orange" for "pink grapefruit". Comment the output: respuesta es ('pink grapefruit', [10, 20, 30], (5, 15, 25))

In [ ]:
# Change value

4. Print the length of tuple1: respuesta es 3

In [ ]:
# Print

5. Sum all the elements of tuple2 and describe your steps and explain each of them. Hint: Use map function.

In [ ]:
# Sum all elemenets of tuple2

6. (Opcional) Generate a new tuple object named as tuple3 with the half values of tuple2. This tuple should be similar as tuple2, tuple of lists. Hint: Use map funciont.

In [ ]:
# New tuple

# 5. Strings

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [ ]:
str1 = 'I am                            too                                                        old'
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]

1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint la respuesta es list

In [ ]:
# Drop duplicated blank spaces

2. Get the number of letters in the string .**Hint: Use `len`function.** la respuesta es 10

In [ ]:
# Number of letters

3. (Optional) Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.** la respuesta es 5

In [ ]:
# Number of blanck spaces

# 6. NumPy

Considere la siguiente información como punto de partida y complete los espacios en blanco

In [ ]:
prueba1 = np.random.randint(0,10,500)
prueba1

In [ ]:
prueba2 = np.arange(50)
np.random.shuffle(prueba2)
prueba2

a. Find the most frequent value in the prueba1 array? El valor más frecuente en el array prueba1 es 7

In [ ]:
# Most frequent value

b. Convert the 1D array prueba2 to a 2D array with 5 rows [[1, 2] [3, 4] [5, 6] [7, 8] [9, 10]]

In [ ]:
# Reshape